### ISSUE TITLE
New v50 spike trap is classified as a modded hazard

### ISSUE THREAD

**Issue by zndrmn** [snaketech-tu/LCHazardsOutside#3]
New v50 spike trap is classified as a modded hazard and doesn't get treated like the other pre-v50 hazards

**Comment by snaketech-tu** [comment]
Hey there! I have been actually working on a v50 update since it came out that just needs a bit more testing.  
I'll try to get it online this week. Thanks for the report!

**Comment by zndrmn** [comment]
Heck yeah!

**Comment by snaketech-tu** [comment]
This is now supported in v1.2.0. Thanks again!
