### ISSUE TITLE
[Issue]SpawnStrategy

### ISSUE THREAD

**Issue by Kmdl14** [snaketech-tu/LCHazardsOutside#5]
You cannot change where the landmines spawn no matter what I input, even with lethal config, it just won't accept any other string

**Comment by snaketech-tu** [comment]
The names are case sensitive so it has to be one of: `MainAndFireExit`, `MainEntranceOnly` or `FireExitsOnly`.  
When the mod is loaded, it is trying to parse these names and if it fails, it goes back to the default.  
Also make sure to reload the game after changing the settings in LethalConfig.  

I just tried a new profile with only this mod in the latest version, Imperium for debugging and the `FireExitsOnly` strategy:  
(Note how the main entrance on the top left does not have any hazards close by)  
![FireExistsOnly](https://github.com/user-attachments/assets/657357a5-de90-459b-9671-6af0b403efcb)  

If the issue persists, can you try to create a new profile only with this mod and see if it works?  
This would rule out any other mod interfering with the config loading.

**Comment by Kmdl14** [comment]
Does this mod have any known conflicts?

**Comment by snaketech-tu** [comment]
There are currently none. Feel free to report any you might encounter though!  
Did you manage to change the config values?
